name: Tests

on:
  pull_request:
    branches:
      - main

jobs:
  generate:
    name: Run tests and upload coverage report
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      RUSTFLAGS: "-Cinstrument-coverage"
      LLVM_PROFILE_FILE: "geohasher-%p-%m.profraw"
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: llvm-tools-preview
      
      - name: Get latest grcov version
        id: grcov-version
        run: |
          GRCOV_VERSION=$(cargo search grcov --limit 1 | grep -oP '(?<=").*(?=")')
          echo "version=$GRCOV_VERSION" >> $GITHUB_OUTPUT
      
      - name: Cache grcov
        uses: actions/cache@v3
        id: cache-grcov
        with:
          path: ~/.cargo/bin/grcov
          key: ${{ runner.os }}-grcov-${{ steps.grcov-version.outputs.version }}

      - name: Install or update grcov
        if: steps.cache-grcov.outputs.cache-hit != 'true'
        run: cargo install grcov --version ${{ steps.grcov-version.outputs.version }}

      - run: cargo build
      - run: cargo test
      - name: Generate coverage report
        run: |
          mkdir -p coverage          
          grcov . --binary-path ./target/debug/ -s . -t lcov --branch --ignore-not-existing -o ./coverage/
          if [ -f ./coverage/lcov ]; then
            echo "Coverage file generated successfully"
            echo "coverage_report=$(base64 -w 0 ./coverage/lcov)" >> $GITHUB_OUTPUT
          else
            echo "Error: lcov file not generated"
            exit 1
          fi
      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v4.2.0
        with:
          file: ./coverage/lcov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }} 
